from typing import Dict, TypedDict, List
from langgraph.graph import StateGraph, END
import logging

from app.nlp.llm_extractor import extract_entities_llm

logger = logging.getLogger(__name__)

# Define State for the Graph
class ExtractionState(TypedDict):
    raw_text: str
    summary: str
    entities: list
    modus_operandi: str
    status: str

def summarize_fir(state: ExtractionState) -> ExtractionState:
    """Summarizes the raw FIR text."""
    # In PHASE 3, we focus on extraction, but here is a placeholder for summary using FallbackManager
    # if required later. For now we just pass through to keep graph structure.
    state["summary"] = "Summary generated by AI"
    state["status"] = "summarized"
    return state

def extract_entities(state: ExtractionState) -> ExtractionState:
    """Extracts entities and events using the real LLM Semantic Extractor."""
    try:
        candidates = extract_entities_llm(state["raw_text"])
        # Map candidates into a serializable dict format for the state
        state["entities"] = [
            {
                "entity_type": c.entity_type,
                "raw_text": c.raw_text,
                "confidence": c.confidence,
                "method": c.extraction_method
            }
            for c in candidates
        ]
        state["status"] = "entities_extracted"
    except Exception as e:
        logger.error(f"FIR LLM Extraction failed: {e}")
        state["entities"] = []
        state["status"] = "failed"
    return state

def match_modus_operandi(state: ExtractionState) -> ExtractionState:
    """Matches the extracted text against known MOs in the vector database."""
    # Placeholder for Phase 4 PGVector integration
    state["modus_operandi"] = "MO match pending Phase 4"
    state["status"] = "completed"
    return state

def build_fir_workflow() -> StateGraph:
    """
    Builds the LangGraph workflow for processing FIRs.
    [PHASE_3_IMPLEMENTED] This graph is wired to the real LLM extractor.
    """
    workflow = StateGraph(ExtractionState)
    
    workflow.add_node("summarize", summarize_fir)
    workflow.add_node("extract", extract_entities)
    workflow.add_node("match_mo", match_modus_operandi)
    
    workflow.set_entry_point("summarize")
    workflow.add_edge("summarize", "extract")
    workflow.add_edge("extract", "match_mo")
    workflow.add_edge("match_mo", END)
    
    return workflow.compile()
