"""add_evidence_text_to_entity_relationships

Revision ID: 2044efa5955a
Revises: 68f826fea910
Create Date: 2026-09-01 19:24:15.490630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2044efa5955a'
down_revision: Union[str, Sequence[str], None] = '68f826fea910'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_relationships', sa.Column('evidence_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_relationships', 'evidence_text')
    # ### end Alembic commands ###
