"""Add resolution evidence to entity candidates

Revision ID: 68f826fea910
Revises: 12142e955ff8
Create Date: 2026-08-31 23:45:29.255706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f826fea910'
down_revision: Union[str, Sequence[str], None] = '12142e955ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entity_candidates', sa.Column('resolution_evidence', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entity_candidates', 'resolution_evidence')
    # ### end Alembic commands ###
