"""Add BaseModel audit fields

Revision ID: b25a48fa9d95
Revises: f945aeb86db6
Create Date: 2026-08-29 21:14:28.538920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b25a48fa9d95'
down_revision: Union[str, Sequence[str], None] = 'f945aeb86db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('canonical_entities', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    op.add_column('canonical_entities', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('canonical_entities', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('canonical_entities', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.alter_column('canonical_entities', 'aliases',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('canonical_entities', 'attributes',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('entity_relationships', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('entity_relationships', sa.Column('created_by', sa.Uuid(), nullable=True))
    op.add_column('entity_relationships', sa.Column('updated_by', sa.Uuid(), nullable=True))
    op.drop_index(op.f('ix_entity_relationships_id'), table_name='entity_relationships')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_entity_relationships_id'), 'entity_relationships', ['id'], unique=False)
    op.drop_column('entity_relationships', 'updated_by')
    op.drop_column('entity_relationships', 'created_by')
    op.drop_column('entity_relationships', 'deleted_at')
    op.alter_column('canonical_entities', 'attributes',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('canonical_entities', 'aliases',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('canonical_entities', 'updated_by')
    op.drop_column('canonical_entities', 'created_by')
    op.drop_column('canonical_entities', 'deleted_at')
    op.drop_column('canonical_entities', 'is_deleted')
    # ### end Alembic commands ###
